### ISSUE TITLE
Node.js warning

### ISSUE THREAD

**Issue by 0neel** [ltDino/android-get-version-action#1]
Hey! Thanks for the action, it helps us integrating our project with SonarCloud easily.

There is just one issue - v1.0 of this plugin gives me the following warning:

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: ltDino/android-get-version-action@v1.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

Are there any plans to update the action to use Node.js 16?

**Comment by ltDino** [comment]
> Hey! Thanks for the action, it helps us integrating our project with SonarCloud easily.
> 
> There is just one issue - v1.0 of this plugin gives me the following warning:
> 
> > Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: ltDino/android-get-version-action@v1.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> 
> Are there any plans to update the action to use Node.js 16?

Sorry, there is no update plan at present, thanks for your attention~
